[package]
name = "rusty-catan-io"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
genawaiter = "0.99.1"
itertools = "0.14.0"
log = "0.4.29"
num = "0.4.3"
rand = "0.9.2"
tinyvec = "1.10.0"
